### ISSUE TITLE
htpasswd from apache2 generates other hashes than sinopia/npm-adduser

### ISSUE THREAD

**Issue by rondonjon** [rlidwka/sinopia-htpasswd#8]
When I use htpasswd from the apache2 distribution to add a user to the file on the command line (is this not how it's meant, despite the name?) an entry like the following is created:

user1:$apr1$pnQSEnhe$AIwFNEA6xOecE7l0/mTeh.

This entry does NOT work in the authentication; the request is denied.

After setting max_users > 0 in config.yaml and creating another user with npm/adduser, an entry with a longer hash has been added:

user2:$6$zAsH+/KRfsOzgw==$LGzgf.I8ctW/day/J6AjZoe8sH5FaznwFb3bR9AEdbCDTojAjul/ZTzN2u95n1dc/m1057SHqHxleZ2DpOI.s.:autocreated 2015-02-08T00:03:45.226Z

Do the tools possibly use different hash algorithms? How should I add an entry to the htpasswd file from the command line if not using the htpasswd tool?

**Comment by rlidwka** [comment]
They are different. Apr1 is apache-specific crypto function based on md5, and sinopia's implementation is a standard crypt(3). We created it for compatibility with nginx, not apache.

You can use SHA or CRYPT (`-d` and `-s` options for htpasswd). Their implementation is the same, but they are considered insecure.

Better idea would be to use `mkpasswd --method=sha-512` instead of `htpasswd`.
